### ISSUE TITLE
pal_network.h not found (mbed os 5.2)

### ISSUE THREAD

**Issue by p03189** [ARMmbed/mbed-client-classic#44]
Hi

I'm trying to build mbed-os-example-client with latest version of mbed-client (v1.18.3)
Target: K64F
Toolchain: gcc-arm-none-eabi-4_9-2015q2

I got error message as following:
[DEBUG] Output: ./mbed-client/mbed-client-classic/mbed-client-classic/m2mconnectionhandlerpimpl.h:27:25: fatal error: pal_network.h: No such file or directory
[DEBUG] Output:  #include "pal_network.h"
[DEBUG] Output:                          ^
[DEBUG] Output: compilation terminated.

I can't find pal_network.h in mbed-os 5 libraries. Please help me to fix this error, thank you.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-1077

**Comment by yogpan01** [comment]
Hi,
Why are you using this repo from master HEAD ? You are not supposed to use this repo directly but get it through released mbed OS version.

**Comment by jankii01** [comment]
Hi,

yes, please use this for latest official mbedOS;

https://github.com/armmbed/mbed-os/tree/mbed-os-5.1

or if you really want the cutting edge, you can get the 5.2 release candidates (not officially released yet).

https://github.com/armmbed/mbed-os/tree/mbed-os-5.2

mbedOS includes the latest version of this repo as well, which has been tested to work.

**Comment by p03189** [comment]
Hi jankii01, 

Thanks for your reply.
